import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import Menu from "./components/navbar/components/Menu";

const lato = Lato({ weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.className} px-3 md:px-6 xl:px-16 flex flex-col items-center`}
      >
        <Navbar />
        <main className="size-full max-w-[1440px] pt-[72px]">{children}</main>
      </body>
    </html>
  );
}
